steps:
  # Debug step to list directory contents
  - name: 'ubuntu'
    args: ['bash', '-c', 'ls -la && pwd']

  # Copy .env file (if you're using one)
  - name: 'ubuntu'
    args: ['bash', '-c', 'cp .env.example .env || true']

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '-f', 'Dockerfile', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - '$REPO_NAME'
    - '--image'
    - 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--set-env-vars'
    - 'AZURE_OPENAI_KEY=${_AZURE_OPENAI_KEY},AZURE_OPENAI_ENDPOINT=${_AZURE_OPENAI_ENDPOINT},AZURE_OPENAI_VERSION=${_AZURE_OPENAI_VERSION},AZURE_OPENAI_DEPLOYMENT=${_AZURE_OPENAI_DEPLOYMENT}'

images:
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'